--- 
modules: 
  blog: true
  documents: false
  galleries: false
  store: true
  events: false
  product: false
  version: 1.0.0
  pages: true
  newsletters: false
  links: false
  members: false
keys: 
  sharethis: 998f13df-36bb-4d5b-96fc-c750d3a55a99
  google_maps: ABQIAAAAcFCYQRnwVUthPL-ySCSjJBSLDG_2ULvcs8_kz7lLyWlTqMYI6BQ3Mk_WENuT5q-vBi1wjshbLJ7aoQ
development_keys: 
  google_maps: ABQIAAAAcFCYQRnwVUthPL-ySCSjJBTJQa0g3IQ9GZqIMmInSLzwtGDKaBS8HXDFpTZcTkemWroqwX691T1xpg
website: 
  name: New Site Ninja Site
  logo_position: top
  demo_message: 
  icon_domain: http://www.site-ninja.com
  domain: domain.com
  demo: false
  template: t3c5
features: 
  testimonials: false
  feature_box: true
  event_registration: true
site_settings: 
  event_title: Event
  blog_title: Blog
  file_up_size: 20
  article_title: Article
  third_level_menu: left
  events_title: Calendar
  links_title: Links
  link_title: Resource
